server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://garritas-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: garritas-venta-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-venta-ms
          __path__: /var/log/garritas/garritas-venta-ms/logs/*.log

  - job_name: garritas-institucion-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-institucion-ms
          __path__: /var/log/garritas/garritas-institucion-ms/logs/*.log

  - job_name: garritas-envio-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-envio-ms
          __path__: /var/log/garritas/garritas-envio-ms/logs/*.log

  - job_name: garritas-citas-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-citas-ms
          __path__: /var/log/garritas/garritas-citas-ms/logs/*.log

  - job_name: garritas-catalogo-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-catalogo-ms
          __path__: /var/log/garritas/garritas-catalogo-ms/logs/*.log

  - job_name: garritas-usuario-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-usuario-ms
          __path__: /var/log/garritas/garritas-usuario-ms/logs/*.log

  - job_name: garritas-pago-ms
    static_configs:
      - targets: [localhost]
        labels:
          application: garritas-pago-ms
          __path__: /var/log/garritas/garritas-pago-ms/logs/*.log
