server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: garritas-venta
              uri: lb://garritas-venta-ms
              predicates:
                - Path=/api/v1/ventas/**
            - id: garritas-institucion
              uri: lb://garritas-institucion-ms
              predicates:
                - Path=/api/v1/sedes/**
            - id: garritas-envio
              uri: lb://garritas-envio-ms
              predicates:
                - Path=/api/v1/envios/**
            - id: garritas-citas
              uri: lb://garritas-citas-ms
              predicates:
                - Path=/api/v1/citas/**
            - id: garritas-catalogo-categorias
              uri: lb://garritas-catalogo-ms
              predicates:
                - Path=/api/v1/categorias/**
            - id: garritas-catalogo-productos
              uri: lb://garritas-catalogo-ms
              predicates:
                - Path=/api/v1/productos/**
            - id: garritas-usuario
              uri: lb://garritas-usuario-ms
              predicates:
                - Path=/api/v1/usuarios/**
            - id: garritas-pago
              uri: lb://garritas-pago-ms
              predicates:
                - Path=/api/v1/pagos/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://garritas-eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
