CREATE TABLE IF NOT EXISTS envios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_venta BIGINT NOT NULL,
    direccion_entrega VARCHAR(255) NOT NULL,
    transportista VARCHAR(100),
    estado VARCHAR(20) NOT NULL,
    fecha_envio TIMESTAMP,
    fecha_entrega_estimada TIMESTAMP,
    PRIMARY KEY (id)
);
